<?php

namespace Database\Seeders;

use App\Models\Destination;
use App\Models\Factory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $destinations = [
            [
                'customer_name' => '1001 VISALIA DC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1001 VISALIA DC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1001 VISALIA DC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1004 BRAMPTON DC',
                'customer_name_two' => '',
                'destination' => 'Canada加拿大',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1004 BRAMPTON DC',
                'customer_name_two' => '',
                'destination' => 'Canada加拿大',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,


            [
                'customer_name' => '1005 VF OUTDOOR MEXICO S.de R.',
                'customer_name_two' => '',
                'destination' => 'Mexico墨西哥',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1005 VF OUTDOOR MEXICO S.de R.',
                'customer_name_two' => '',
                'destination' => 'Mexico墨西哥',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,


            [
                'customer_name' => 'D00028 SUN AND SAND SPORTS LLC',
                'customer_name_two' => '',
                'destination' => 'UAE,Dubai阿联酋,迪拜',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'D00045 VF ISRAEL LTD',
                'customer_name_two' => '',
                'destination' => 'Israel以色列',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D00079 VF ISRAEL LTD',
                'customer_name_two' => '',
                'destination' => 'Israel以色列',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D040 VF Prague One DC (CZ)',
                'customer_name_two' => '',
                'destination' => 'Czech捷克',
                'brand' => 'NAPAPIJRI',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D040S VF Prague One DC (CZ)',
                'customer_name_two' => '',
                'destination' => 'Czech捷克',
                'brand' => 'NAPAPIJRI',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D05018 SUN AND SAND SPORTS LLC',
                'customer_name_two' => '',
                'destination' => 'UAE,Dubai阿联酋,迪拜',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D05019 ALI ABDULWAHAB AL-MUTAW',
                'customer_name_two' => '',
                'destination' => 'Kuwait科威特',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D060 VF EDC (BE)',
                'customer_name_two' => '',
                'destination' => 'Belgium比利时',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D060S VF EDC (BE)',
                'customer_name_two' => '',
                'destination' => 'Belgium比利时',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D080 VF Northern Europe',
                'customer_name_two' => '',
                'destination' => 'UK英国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D080 VF Northern Europe',
                'customer_name_two' => '',
                'destination' => 'UK英国',
                'brand' => 'TNF',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D060 VF Northern Europe',
                'customer_name_two' => '',
                'destination' => 'UK英国',
                'brand' => 'TNF',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D080 VF Northern Europe',
                'customer_name_two' => '',
                'destination' => 'UK英国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'Hamburg Idstein',
                'customer_name_two' => '',
                'destination' => 'Idstein德国伊德斯坦因',
                'brand' => 'JACKWOLFSKIN',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'JP NaritaAptTokyo',
                'customer_name_two' => '',
                'destination' => 'Japan日本',
                'brand' => 'JACKWOLFSKIN',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'NWT Jack Wolfskin Ausruestung fur',
                'customer_name_two' => '',
                'destination' => 'Hamburg德国汉堡',
                'brand' => 'JACKWOLFSKIN',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'OSACS SECTOR APPAREL CC',
                'customer_name_two' => '',
                'destination' => 'South Africa南非',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'OVMOM VF Malaysia Office',
                'customer_name_two' => '',
                'destination' => 'Malaysia马来西亚',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'OVMOM VF Malaysia Office',
                'customer_name_two' => '',
                'destination' => 'Malaysia马来西亚',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'SH Shanghai',
                'customer_name_two' => '',
                'destination' => 'Shanghai中国上海',
                'brand' => 'JACKWOLFSKIN',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T007 LF Logistics (Taiwan) LTD.',
                'customer_name_two' => '',
                'destination' => 'Taiwan台湾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T909 GOLDWIN JAPAN - JAPAN',
                'customer_name_two' => '',
                'destination' => 'Japan日本',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T910 GOLDWIN KOREA - KOREA',
                'customer_name_two' => '',
                'destination' => 'South Korea韩国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T953 LF Logistics HK Limited',
                'customer_name_two' => '',
                'destination' => 'Hong Kong香港',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T963 OUTDOOR VENTURE - SINGAPORE',
                'customer_name_two' => '',
                'destination' => 'Singapore新加坡',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T970 VF APPAREL (SZ) LTD-SHA',
                'customer_name_two' => '',
                'destination' => 'Shanghai上海',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'US NADC-JW',
                'customer_name_two' => '',
                'destination' => 'Dallas美国达拉斯',
                'brand' => 'JACKWOLFSKIN',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'VNSGP LF Logistics Services Pte Ltd',
                'customer_name_two' => '',
                'destination' => 'Singapore新加坡',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W001 LF Logistics HK Limited',
                'customer_name_two' => '',
                'destination' => 'Hong Kong香港',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W001 LF Logistics HK Limited',
                'customer_name_two' => '',
                'destination' => 'Hong Kong香港',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'W001 Maersk Contract Logistics (Hong Kong) Limited',
                'customer_name_two' => '',
                'destination' => 'Hong Kong香港',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W00410 KunShan CDC',
                'customer_name_two' => '',
                'destination' => 'China中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W00410 KunShan CDC',
                'customer_name_two' => '',
                'destination' => 'China中国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W00560 LF Logistics Services Pte Ltd',
                'customer_name_two' => '',
                'destination' => 'Singapore新加坡',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'W100 Kunshan Central DC',
                'customer_name_two' => '',
                'destination' => 'China中国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'W300 Korea DC',
                'customer_name_two' => '',
                'destination' => 'South Korea韩国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'W500 Malaysia DC',
                'customer_name_two' => '',
                'destination' => 'Malaysia马来西亚',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'W601 LF Logistics Services Pte Ltd',
                'customer_name_two' => '',
                'destination' => 'Singapore新加坡',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W601 LF Logistics Services Pte Ltd',
                'customer_name_two' => '',
                'destination' => 'Singapore新加坡',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'W601 Singapore DC',
                'customer_name_two' => '',
                'destination' => 'Singapore新加坡',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'W60501 Maersk Contract Logistics (Hong Kong) Limited',
                'customer_name_two' => '',
                'destination' => 'Hong Kong香港',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60501 Maersk Contract Logistics (Hong Kong) Limited',
                'customer_name_two' => '',
                'destination' => 'Hong Kong香港',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'W60510 KunShan CDC',
                'customer_name_two' => '',
                'destination' => 'China中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60510 KunShan CDC',
                'customer_name_two' => '',
                'destination' => 'China中国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60530 Korea DC',
                'customer_name_two' => '',
                'destination' => 'South Korea韩国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60550 LF LOGISTICS SERVICES (M) SDN',
                'customer_name_two' => '',
                'destination' => 'Malaysia马来西亚',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60570 Maersk Contract Logistics (Taiwan) Limited, Taiwan Branch',
                'customer_name_two' => '',
                'destination' => 'Taiwan台湾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60570 Maersk Contract Logistics (Taiwan) Limited, Taiwan Branch',
                'customer_name_two' => '',
                'destination' => 'Taiwan台湾',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60570 Maersk Contract Logistics (Taiwan) Limited, Taiwan Branch',
                'customer_name_two' => '',
                'destination' => 'Taiwan台湾',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1401 NORFOLK VISALIA DC MTV PATRIOT CENTER',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1401 NORFOLK MTV DC under region US–MARMAXX MTV PATRIOT CENTER',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '9992 VANCOUVER BRAMPTON DC PRS POWERHOUSE RETAIL SERVICES',
                'customer_name_two' => '',
                'destination' => 'Canada加拿大',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '9992 VANCOUVER PRS DC under region US MARMAXX(TJX CANADA) ',
                'customer_name_two' => '',
                'destination' => 'Canada加拿大',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 L AND S CORPORATION - JAPAN',
                'customer_name_two' => '',
                'destination' => 'Japan日本',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 KOREA - LEENOS',
                'customer_name_two' => '',
                'destination' => 'South Korea韩国',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 MANEEYA CONCEPTS CO., LTD',
                'customer_name_two' => '',
                'destination' => 'Thailand泰国',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60510 CHINA DUTY FREE GROUP',
                'customer_name_two' => '',
                'destination' => 'China中国',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60510 VF CHINA Limited',
                'customer_name_two' => '',
                'destination' => 'China中国',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 INDONESIA-P.T. MITRA ADIPERKASA TBK',
                'customer_name_two' => '',
                'destination' => 'Indonesia印度尼西亚',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 GREYHOUND MARKETING CORP',
                'customer_name_two' => '',
                'destination' => 'Philippine菲律宾',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W001 Ram Pacific',
                'customer_name_two' => '',
                'destination' => 'Malaysia马来西亚',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,


            [
                'customer_name' => 'D05045 ONCE CERO CUATRO S.A. DE C.V',
                'customer_name_two' => '',
                'destination' => 'Mexico墨西哥',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W601 L AND S CORPORATION',
                'customer_name_two' => '',
                'destination' => 'Singapore新加坡',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 LF Logistics Service Pte Ltd',
                'customer_name_two' => '',
                'destination' => 'Singapore新加坡',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D05191 UNITED ARAB EMIRATES + JASHANMAL',
                'customer_name_two' => '',
                'destination' => 'UAE,Dubai阿联酋,迪拜',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D05109 COMERCIAL ASTE DE IMPORTACAO LTDA',
                'customer_name_two' => '',
                'destination' => 'Brazil巴西',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D05181 KOMAX SA',
                'customer_name_two' => '',
                'destination' => 'Chile智利',
                'brand' => 'KIPLING',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '80 Williamson-Dickie, a division of VF Outdoor, LLC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => '75C WILLIAMSON DICKIE CANADA COMPANY',
                'customer_name_two' => '',
                'destination' => 'CANADA加拿大',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => 'D040 VF Prague One DC (CZ)',
                'customer_name_two' => '',
                'destination' => 'EU欧洲',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => 'W60510 Kunshan Central DC',
                'customer_name_two' => '',
                'destination' => 'China中国',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => 'W60540 DHL Supply Chain Ltd. CO VF Japan Co.ltd',
                'customer_name_two' => '',
                'destination' => 'Japan日本',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => 'W002 THAI OUTDOOR SPORT CO LTD',
                'customer_name_two' => '',
                'destination' => 'Thailand泰国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC for Dropship',
                'customer_name_two' => 'THAI OUTDOOR SPORT CO LTD',
                'destination' => 'Thailand泰国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,

            [
                'customer_name' => 'T007 LF Logistics (Taiwan) LTD.',
                'customer_name_two' => '',
                'destination' => 'Taiwan台湾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC for Dropship',
                'customer_name_two' => 'Primer Kenrich SDN. BHD (611792-M)',
                'destination' => 'Malaysia马来西亚',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC for Dropship',
                'customer_name_two' => 'UNIGLOBE TRAVELWARE CO., INC',
                'destination' => 'Philippines菲律宾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W002 VFSOS Virtual DC for Dropship',
                'customer_name_two' => '',
                'destination' => 'Philippines菲律宾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1001 VF Outdoor, Inc. VISALIA DC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => '1004 VF Outdoor Canada, Co.BRAMPTON DC',
                'customer_name_two' => '',
                'destination' => 'Canada加拿大',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => 'EU VF ABX (BE)',
                'customer_name_two' => '',
                'destination' => 'EU',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 SERTRADING BR LTDA',
                'customer_name_two' => '',
                'destination' => 'Brazil巴西',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1009 Dropship US',
                'customer_name_two' => 'SAN MAR CORPPORATION',
                'destination' => 'USA美国',
                'brand' => 'TNF',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W601 LF Logistics Services Pte Ltd',
                'customer_name_two' => 'Adventure Outdoor Gear Co.PVT.Ltd',
                'destination' => 'Singapore新加坡',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W601 LF Logistics Services Pte Ltd',
                'customer_name_two' => 'VF DC',
                'destination' => 'Singapore新加坡',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W601 LF Logistics Services Pte Ltd',
                'customer_name_two' => 'Sherpa Adventure Outlet (P.) Ltd',
                'destination' => 'Singapore新加坡',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'LOGISTIS SOLUTIONS SA DE CV',
                'destination' => 'EL SALVADOR萨尔瓦多',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SUPREME OVERSEAS CORP',
                'destination' => 'Panama巴拿马',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'ACCUR8 DISTRIBUTION INC',
                'destination' => 'Panama巴拿马',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'BERSALLES GROUP INC',
                'destination' => 'Colombia哥伦比亚',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'TNF COMERCIAL E IMPORTADORA LTDA',
                'destination' => 'Brazil巴西',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'KOMAX PERU SAC',
                'destination' => 'Peru秘鲁',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'KOMAX SA',
                'destination' => 'Chile智利',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'PT MULTIFORTUNA SINARDELTA',
                'destination' => 'Indonesia印度尼西亚',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'RETAIL CAPS',
                'destination' => 'Mexico墨西哥',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'FORUS SA',
                'destination' => 'Chile智利',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'Colombia哥伦比亚',
                'destination' => 'ACCUR8 DISTR CO Dynamo Distr SAS',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'ZEKOV SA',
                'destination' => 'Panama巴拿马',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'PERU FORUS S A',
                'destination' => 'Peru秘鲁',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'PELEG NIL LTD',
                'destination' => 'Israel以色列',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'TRIALAND SA',
                'destination' => 'Argentina阿根廷',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SEAGER INC PTE LTD',
                'destination' => 'Singapore新加坡',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SAVE COMERCIAL E IMPORTADORA LTDA',
                'destination' => 'Brazil巴西',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'ALTMON BRANDS S A',
                'destination' => 'Costa Rica哥斯达黎加',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'CAMPERLAND INTERNATIONAL LTD',
                'destination' => 'Taiwan台湾',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SOVANNKIRI IMPORT EXPORT CO LTD',
                'destination' => 'Cambodia柬埔寨',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SOURCE RITE INTERNATIONAL FZCO',
                'destination' => 'UAE 阿联酋,迪拜',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'MUSINSA TRADING CO LTD',
                'destination' => 'South Korea韩国',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SHANGHAI TOP FORWARD TRADING',
                'destination' => 'China中国',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'TEXAS PEAK PTY LTD',
                'destination' => 'Australia澳大利亚',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SUNGLASS PALACE PVT LTD',
                'destination' => 'India印度',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1009 Dropship',
                'customer_name_two' => 'US ACADEMY LTD',
                'destination' => 'Academy',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'CHANDRA KUMARI TRADING',
                'destination' => 'Nepal尼泊尔',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SUPERDEPORTE SA',
                'destination' => 'Ecuador厄瓜多尔',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'URUFORUS SA',
                'destination' => 'Uruguay New乌拉圭',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'ALI ABDULWAHAB AL MUTAWA',
                'destination' => 'Kuwait科威特',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SFI AFRICA CORP',
                'destination' => 'Nigeria尼日利亚',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'UNIGLOBE TRAVELWARE CO INC',
                'destination' => 'Philippines菲律宾',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SFI AFRICA CORP 2',
                'destination' => 'South Africa南非',
                'brand' => '',
                'type' => '',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'BEATTIE MATHESON LTD',
                'destination' => 'New Zealand新西兰',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'RETAIL ONE CO LTD',
                'destination' => 'Thailand泰国',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'MULTI FAME LIMITED',
                'destination' => 'Hong Kong香港',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'PASSAGE NETWORK SDN BHD',
                'destination' => 'Malaysia马来西亚',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'AL ANOUD TRADING CO',
                'destination' => 'Jordan约旦',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'UNIGLOBE LLC',
                'destination' => 'Japan日本',
                'brand' => 'JANSPORT',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'USA美国',
                'customer_name_two' => '',
                'destination' => '',
                'brand' => 'ADVANTUS',
                'type' => 'EQUIPMENT',
            ] ,
            //VANSSS EQUIPMENT
            [
                'customer_name' => '1001 VISALIA DC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1002 SANTA FE SPRINGS DC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1023 South Ontario DC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1020 JONESTOWN DC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1004 BRAMPTON DC',
                'customer_name_two' => 'VF Outdoor (Canada), Co.',
                'destination' => 'Canada加拿大',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D010 VF Prague DC CZ',
                'customer_name_two' => '',
                'destination' => 'Czech捷克',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D010S VF Prague DC CZ',
                'customer_name_two' => '',
                'destination' => 'Czech捷克',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D080 VF Northern Europe',
                'customer_name_two' => '',
                'destination' => 'UK英国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1005 VF OUTDOOR MEXICO S.de R.',
                'customer_name_two' => '',
                'destination' => 'Mexico墨西哥',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'VD10 Day One As',
                'customer_name_two' => '',
                'destination' => 'Norway',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D00045 VF ISRAEL LTD',
                'customer_name_two' => '',
                'destination' => 'Israel以色列',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SERTRADING BR LTDA',
                'destination' => 'Brazil巴西',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'GRIMOLDI S.A',
                'destination' => 'Argentina',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'MERCOSUR SPORT WORLD CO',
                'destination' => 'PARAGUAY',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'GRIMURU S.A',
                'destination' => 'URUGUAY',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'ACCUR8 DISTRIBUTION INC',
                'destination' => 'PANAMA',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'FORUS SA',
                'destination' => 'CHILE',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'ACCENT FOOTWEAR LTD',
                'destination' => 'New Zealand',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'ACCENT GROUP PTY',
                'destination' => 'Australia',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'THAI OUTDOOR SPORT CO LTD',
                'destination' => 'Thailand',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'PT. NAVYA RETAIL INDONESIA',
                'destination' => 'Indonesia',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'VENICE 66 FASHION',
                'destination' => 'Philippines',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'OCSDS Reviva Technology (Pty) Ltd',
                'customer_name_two' => 'Reviva Technology (Pty) Ltd',
                'destination' => 'South Africa',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'VINH QUANG MINH',
                'destination' => 'Vietnam',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60501 Maersk Contract Logistics (Hong Kong) Limited',
                'customer_name_two' => 'VF HK LTD',
                'destination' => 'Hong Kong香港',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60510 Kunshan Central DC',
                'customer_name_two' => 'VF China Limited',
                'destination' => 'China中国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W302 Korea DC',
                'customer_name_two' => 'ABC MART KOREA INC',
                'destination' => 'South Korea韩国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60550 LF LOGISTICS SERVICES (M) SDN',
                'customer_name_two' => 'VF Brands Malaysia SdnBhd',
                'destination' => 'Malaysia马来西亚',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60570 Maersk Contract Logistics (Taiwan) Limited, Taiwan Branch',
                'customer_name_two' => 'VF Brands Taiwan Limited',
                'destination' => 'Taiwan台湾',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W700 VF Brands Taiwan Limited',
                'customer_name_two' => '',
                'destination' => 'Taiwan台湾',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W702 ABC-MART TAIWAN, INC.',
                'customer_name_two' => '',
                'destination' => 'Taiwan台湾',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W400 VF Japan Limited',
                'customer_name_two' => '',
                'destination' => 'Japan',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60540 VF Japan Limited',
                'customer_name_two' => '',
                'destination' => 'Japan',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W402 ABC Mart Inc.',
                'customer_name_two' => '',
                'destination' => 'Japan',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W00410 KunShan CDC',
                'customer_name_two' => 'VF China Limited',
                'destination' => 'China中国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W00560 LF Logistics Services Pte Ltd',
                'customer_name_two' => 'VF Brands Pte. Ltd',
                'destination' => 'Singapore新加坡',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W100 Kunshan Central DC',
                'customer_name_two' => 'VF China Limited',
                'destination' => 'China中国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W300 Korea DC',
                'customer_name_two' => 'VF Korea LTD',
                'destination' => 'South Korea韩国',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W500 Malaysia DC',
                'customer_name_two' => 'VF Brands Malaysia SdnBhd',
                'destination' => 'Malaysia马来西亚',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W601 LF Logistics Services Pte Ltd',
                'customer_name_two' => 'VF Brands Pte. Ltd',
                'destination' => 'Singapore新加坡',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'OVMOM VF Malaysia Office',
                'customer_name_two' => 'VF Brands Malaysia SdnBhd',
                'destination' => 'Malaysia马来西亚',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'VNSGP LF Logistics Services Pte Ltd',
                'customer_name_two' => 'VF Brands Pte. Ltd',
                'destination' => 'Singapore新加坡',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60560 LF Logistics Services Pte Ltd',
                'customer_name_two' => 'VF Brands Pte. Ltd',
                'destination' => 'Singapore新加坡',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W001 LF Logistics HK Limited',
                'customer_name_two' => 'VF HK LTD',
                'destination' => 'Hong Kong香港',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D00028 SUN AND SAND SPORTS LLC',
                'customer_name_two' => 'SUN AND SAND SPORTS LLC',
                'destination' => 'UAE,Dubai阿联酋,迪拜',
                'brand' => 'VANS',
                'type' => 'EQUIPMENT',
            ] ,
            //VANSEQUIPMENT
            //EASTPAK EQUIPMENT
            [
                'customer_name' => 'D050 VF ABX (BE)',
                'customer_name_two' => '',
                'destination' => 'EU欧洲',
                'brand' => 'EASTPAK',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1004 BRAMPTON DC',
                'customer_name_two' => '',
                'destination' => 'CA',
                'brand' => 'EASTPAK',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '1001 VISALIA DC',
                'customer_name_two' => '',
                'destination' => 'USA',
                'brand' => 'EASTPAK',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'T910 GOLDWIN KOREA',
                'customer_name_two' => '',
                'destination' => 'SOUTH KOREA',
                'brand' => 'EASTPAK',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D05063 ACTUALLY PTE LTD',
                'customer_name_two' => '',
                'destination' => 'Singapore',
                'brand' => 'EASTPAK',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D05129 JASHANMAL NATIONAL COMP. LLC',
                'customer_name_two' => '',
                'destination' => 'DUBAI',
                'brand' => 'EASTPAK',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D05184  COSIMO FRANCE/GO SPORT',
                'customer_name_two' => '',
                'destination' => 'FRANCE',
                'brand' => 'EASTPAK',
                'type' => 'EQUIPMENT',
            ] ,
            //EASTPAK EQUIPMENT
            //DICKIES EQUIPMENT
            [
                'customer_name' => '0080 Williamson-Dickie, a division of VF Outdoor, LLC',
                'customer_name_two' => '',
                'destination' => 'USA美国',
                'brand' => 'DICKIES',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => '75C  WILLIAMSON DICKIE CANADA COMPANY',
                'customer_name_two' => '',
                'destination' => 'CANADA加拿大',
                'brand' => 'DICKIES',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'D040 VF Prague One DC (CZ)',
                'customer_name_two' => '',
                'destination' => 'EU欧洲',
                'brand' => 'DICKIES',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60510 Kunshan Central DC',
                'customer_name_two' => '',
                'destination' => 'China中国',
                'brand' => 'DICKIES',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60540 DHL Supply Chain Ltd. C/O VF Japan Co.ltd',
                'customer_name_two' => '',
                'destination' => 'Japan日本',
                'brand' => 'DICKIES',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60501 Maersk Contract Logistics (Hong Kong) Limited',
                'customer_name_two' => '',
                'destination' => 'Hongkong香港',
                'brand' => 'DICKIES',
                'type' => 'EQUIPMENT',
            ] ,
            [
                'customer_name' => 'W60570  Maersk Contract Logistics (Taiwan) Limited, Taiwan Branch',
                'customer_name_two' => '',
                'destination' => 'Taiwan台湾',
                'brand' => 'DICKIES',
                'type' => 'EQUIPMENT',
            ] ,
            //DICKIES EQUIPMENT
            //TNF APPAREL ADDED
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SERTRADING BR LTDA',
                'destination' => 'Brazil巴西',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SISTEMAS AEREOS SA DE CV',
                'destination' => 'EL SALVADOR萨尔瓦多',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'BLU LOGISTICS',
                'destination' => 'Panama巴拿马',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'JUST US S A',
                'destination' => 'Argentina阿根廷',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'GRIMOLDI SA',
                'destination' => 'Argentina阿根廷',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            //TNF APPAREL ADDED
        ];

        $destinations_ningbo = [
            [
                'customer_name' => '0025 VF Hong Kong Limited',
                'customer_name_two' => '',
                'destination' => 'HONG KONG香港',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '0050 VF Korea LLC',
                'customer_name_two' => 'KOREA韩国',
                'destination' => '',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1001 Visalia DC',
                'customer_name_two' => '',
                'destination' => 'UNITED STATES美国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1002 Santa Fe Springs DC',
                'customer_name_two' => '',
                'destination' => 'UNITED STATES美国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1004 BRAMPTON DC',
                'customer_name_two' => 'VF Outdoor (Canada), Co.',
                'destination' => 'CANADA加拿大',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1005 VF Outdoor Mexico S de R L D',
                'customer_name_two' => '',
                'destination' => 'MEXICO墨西哥',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'ACCUR8 DISTRIBUTION INC OCEAN BUSINESS PLAZA',
                'destination' => 'PANAMA巴拿马',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'GRIMOLDI SA TAX ID # 30 50078129 3',
                'destination' => 'ARGENTINA阿根廷',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'KOMAX PERU SAC',
                'destination' => 'PERU秘鲁',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'KOMAX SA',
                'destination' => 'CHILE智利',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'LOGISTIC SOLUTIONS SA DE CV ADOC INTL TRADING',
                'destination' => 'EL SALVADOR萨尔瓦多',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SUPREME OVERSEAS CORP RONNIE MIZRACHI EDIFICIO NO 1',
                'destination' => 'PANAMA巴拿马',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'TNF COMERCIAL E IMPORTADORA LTDA CNPJ 10 718 110 0001 47',
                'destination' => 'BRAZIL巴西',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1013 MARKETING MEXICO',
                'customer_name_two' => '',
                'destination' => 'MEXICO墨西哥',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1013 MARKETING VANS MARKETING',
                'customer_name_two' => '',
                'destination' => 'MEXICO墨西哥',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1014 Dropship CA',
                'customer_name_two' => 'Kristen Etter',
                'destination' => 'CANADA加拿大',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1014 Dropship CA',
                'customer_name_two' => 'Melanie Picotte',
                'destination' => 'CANADA加拿大',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1014 Dropship CA',
                'customer_name_two' => 'Tiffany Mckenna',
                'destination' => 'CANADA加拿大',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1020 Jonestown DC',
                'customer_name_two' => '',
                'destination' => 'UNITED STATES美国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D060 VF EDC (BE)',
                'customer_name_two' => '',
                'destination' => 'BELGIUM比利时',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D080 VF Northern Europe',
                'customer_name_two' => '',
                'destination' => 'UNITED KINGDOM英国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'ORTLA Reviva Technology (Pty) Ltd.',
                'customer_name_two' => '',
                'destination' => 'SOUTH AFRICA南非',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'OSACS SECTOR APPAREL C.C.',
                'customer_name_two' => '',
                'destination' => 'SOUTH AFRICA南非',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'OSHPC VF China Limited-Shanghai office',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'OTALN NEW ZEALAND',
                'customer_name_two' => 'True Alliance NZ Ltd (Dist)',
                'destination' => 'NEW ZEALAND新西兰',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'SHMKT VF China Ltd-SHA office-Market',
                'customer_name_two' => 'VF China Limited',
                'destination' => 'CHINA中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T909 Goldwin Inc',
                'customer_name_two' => '',
                'destination' => 'JAPAN日本',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T910 GOLDWIN KOREA',
                'customer_name_two' => 'Youngone Outdoor - Korea',
                'destination' => 'KOREA韩国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T915 VFSOS Virtual DC',
                'customer_name_two' => 'Uniglobe Travelware (Dist)',
                'destination' => 'PHILIPPINES菲律宾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T948 VANTAGE POINT',
                'customer_name_two' => 'True Alliance Brands Pty Ltd (Dist)',
                'destination' => 'AUSTRALIA澳大利亚',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T970 LF  Logistics （China）Co., Ltd',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T970 KunShan CDC',
                'customer_name_two' => 'VF China Limited',
                'destination' => 'CHINA中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'VFTW VF Brands Taiwan Limited',
                'customer_name_two' => '',
                'destination' => 'TAIWAN台湾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W100 China Sample DC',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W100 KunShan CDC',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W100 Kunshan Central DC',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W400 DHL Supply Chain Ltd.',
                'customer_name_two' => '',
                'destination' => 'JAPAN日本',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W500 LF LOGISTICS SERVICES (M) SDN BHD',
                'customer_name_two' => '',
                'destination' => 'MALAYSIA马来西亚',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W601 Dropship APAC',
                'customer_name_two' => 'ADVENTURE OUTDOOR GEAR CO. PVT. LTD.',
                'destination' => 'NEPAL尼泊尔',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W601 Dropship APAC',
                'customer_name_two' => 'LF Logistics Services Pte Ltd',
                'destination' => 'SINGAPORE新加坡',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W601 Dropship APAC',
                'customer_name_two' => 'PT Giordano Indonesia',
                'destination' => 'INDONESIA印尼',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W601 Dropship APAC',
                'customer_name_two' => 'SHERPA ADVENTURE OUTLET (P.) LTD',
                'destination' => 'NEPAL尼泊尔',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'ACCENT GROUP PTY LTD',
                'destination' => 'AUSTRALIA澳大利亚',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'OUTDOOR VENTURE PTE LTD',
                'destination' => 'SINGAPORE新加坡',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'Primer Kenrich SDN. BHD (611792-M)',
                'destination' => 'MALAYSIA马来西亚',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'PT Giordano Indonesia',
                'destination' => 'INDONESIA印尼',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'THAI OUTDOOR SPORT CO LTD',
                'destination' => 'THAILAND泰国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'True Alliance Brands Pty Ltd.',
                'destination' => 'AUSTRALIA澳大利亚',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'UNIGLOBE TRAVELWARE CO., INC',
                'destination' => 'PHILIPPINES菲律宾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60501 Maersk Contract Logistics (HK) Ltd',
                'customer_name_two' => '',
                'destination' => 'HONG KONG香港',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60510 KunShan CDC',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60530 Korea DC DHL Supply Chain (Korea) Ltd.',
                'customer_name_two' => '',
                'destination' => 'KOREA韩国',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60540 DHL Supply Chain Ltd. CO VF Japan Co.ltd',
                'customer_name_two' => '',
                'destination' => 'JAPAN日本',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60542 ABC-MART SOUKA WAREHOUSE',
                'customer_name_two' => '',
                'destination' => 'JAPAN日本',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60550 VF Brands Malaysia SdnBhd',
                'customer_name_two' => 'LF LOGISTICS SERVICES (M) SDN BHD',
                'destination' => 'MALAYSIA马来西亚',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60570 Maersk Contract Logistics (TW) Ltd',
                'customer_name_two' => '',
                'destination' => 'TAIWAN台湾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60572 ABC-MART TAIWAN, INC.',
                'customer_name_two' => 'ABC Mart-Warehouse',
                'destination' => 'TAIWAN台湾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W700 VF Brands Taiwan Limited',
                'customer_name_two' => '',
                'destination' => 'TAIWAN台湾',
                'brand' => 'TNF',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '0025 VF Hong Kong Limited',
                'customer_name_two' => '',
                'destination' => 'HONG KONG香港',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '0050 VF Korea LLC',
                'customer_name_two' => '',
                'destination' => 'KOREA韩国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1001 Visalia DC',
                'customer_name_two' => '',
                'destination' => 'UNITED STATES美国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1002 Santa Fe Springs DC',
                'customer_name_two' => '',
                'destination' => 'UNITED STATES美国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1004 BRAMPTON DC',
                'customer_name_two' => 'VF Outdoor (Canada), Co.',
                'destination' => 'CANADA加拿大',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1005 VF Outdoor Mexico S de R L D',
                'customer_name_two' => '',
                'destination' => 'MEXICO墨西哥',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'FORUS SA ATTN NOELIA CARVAJAL',
                'destination' => 'CHILE智利',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'GRIMOLDI SA TAX ID # 30 50078129 3',
                'destination' => 'ARGENTINA阿根廷',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'GRIMURU S A',
                'destination' => 'URUGUAY乌拉圭',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1010 Dropship International',
                'customer_name_two' => 'SERTRADING BR LTDA CNPJ 04 626 426 0007 00',
                'destination' => 'BRAZIL巴西',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1013 MARKETING MEXICO',
                'customer_name_two' => '',
                'destination' => 'MEXICO墨西哥',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1013 MARKETING VANS MARKETING',
                'customer_name_two' => '',
                'destination' => 'MEXICO墨西哥',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1020 Jonestown DC',
                'customer_name_two' => '',
                'destination' => 'UNITED STATES美国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => '1023 South Ontario DC',
                'customer_name_two' => '',
                'destination' => 'UNITED STATES美国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D060 VF EDC (BE)',
                'customer_name_two' => '',
                'destination' => 'BELGIUM比利时',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'D080 VF Northern Europe',
                'customer_name_two' => '',
                'destination' => 'UNITED KINGDOM英国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'ORTLA Reviva Technology (Pty) Ltd.',
                'customer_name_two' => '',
                'destination' => 'SOUTH AFRICA南非',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'OSACS SECTOR APPAREL C.C.',
                'customer_name_two' => '',
                'destination' => 'SOUTH AFRICA南非',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T909 Goldwin Inc',
                'customer_name_two' => '',
                'destination' => 'JAPAN日本',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'T910 GOLDWIN KOREA',
                'customer_name_two' => 'Youngone Outdoor - Korea',
                'destination' => 'KOREA韩国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'VFTW VF Brands Taiwan Limited',
                'customer_name_two' => '',
                'destination' => 'TAIWAN台湾',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W100 China Sample DC',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W100 KunShan CDC',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W100 Kunshan Central DC',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W400 DHL Supply Chain Ltd.',
                'customer_name_two' => '',
                'destination' => 'JAPAN日本',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W500 LF LOGISTICS SERVICES (M) SDN BHD',
                'customer_name_two' => '',
                'destination' => 'MALAYSIA马来西亚',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W601 Dropship APAC',
                'customer_name_two' => 'LF Logistics Services Pte Ltd',
                'destination' => 'SINGAPORE新加坡',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'ACCENT FOOTWEAR LIMITED',
                'destination' => 'NEW ZEALAND新西兰',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'ACCENT GROUP PTY LTD',
                'destination' => 'AUSTRALIA澳大利亚',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W602 VFSOS Virtual DC',
                'customer_name_two' => 'OUTDOOR VENTURE PTE LTD',
                'destination' => 'SINGAPORE新加坡',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60501 Maersk Contract Logistics (HK) Ltd',
                'customer_name_two' => '',
                'destination' => 'HONG KONG香港',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60510 KunShan CDC',
                'customer_name_two' => '',
                'destination' => 'CHINA中国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60530 Korea DC DHL Supply Chain (Korea) Ltd.',
                'customer_name_two' => '',
                'destination' => 'KOREA韩国',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60540 DHL Supply Chain Ltd. CO VF Japan Co.ltd',
                'customer_name_two' => '',
                'destination' => 'JAPAN日本',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60542 ABC-MART SOUKA WAREHOUSE',
                'customer_name_two' => '',
                'destination' => 'JAPAN日本',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60550 VF Brands Malaysia SdnBhd',
                'customer_name_two' => 'LF LOGISTICS SERVICES (M) SDN BHD',
                'destination' => 'MALAYSIA马来西亚',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60570 Maersk Contract Logistics (TW) Ltd',
                'customer_name_two' => '',
                'destination' => 'TAIWAN台湾',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W60572 ABC-MART TAIWAN, INC.',
                'customer_name_two' => 'ABC Mart-Warehouse',
                'destination' => 'TAIWAN台湾',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,
            [
                'customer_name' => 'W700 VF Brands Taiwan Limited',
                'customer_name_two' => '',
                'destination' => 'TAIWAN台湾',
                'brand' => 'VANS',
                'type' => 'APPAREL',
            ] ,

        ];

        $factory_number = Factory::where('active',1)->first()->factory_number;
        if($factory_number === "0000721415"){
            foreach($destinations as $destination){
                Destination::create($destination);
            }
        }elseif($factory_number === "0000721414"){
            foreach($destinations_ningbo as $destination){
                Destination::create($destination);
            }
        }

    }
}

